namespace QuanLyTrungTamTiemChung.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addidentity : DbMigration
    {
        public override void Up()
        {
            Sql(@"ALTER TABLE [dbo].[LOVACXIN] DROP CONSTRAINT [FK_dbo.LOVACXIN_dbo.VACXIN_VACXIN_MAVX]");
            DropForeignKey("dbo.PHIEUTIEM", "MABS", "dbo.BACSI");
            DropForeignKey("dbo.PHIEUKHAM", "MABS", "dbo.BACSI");
            DropForeignKey("dbo.BACSI", "MACS", "dbo.COSO");
            DropForeignKey("dbo.KHO", "MACS", "dbo.COSO");
            DropForeignKey("dbo.NHANVIEN", "MACS", "dbo.COSO");
            DropForeignKey("dbo.PHIEUDANGKY", "MACS", "dbo.COSO");
            DropForeignKey("dbo.LOAIVACXIN", "MAKHO", "dbo.KHO");
            DropForeignKey("dbo.PHIEUXUAT", "MAKHODICH", "dbo.KHO");
            DropForeignKey("dbo.PHIEUXUAT", "MAKHONGUON", "dbo.KHO");
            DropForeignKey("dbo.VACXIN", "MALOAI", "dbo.LOAIVACXIN");
            DropForeignKey("dbo.LOVACXIN", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_GOIVX", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_PHIEUTIEM", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_PHIEUXUAT", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_GOIVX", "MAGOIVX", "dbo.GOIVACXIN");
            DropForeignKey("dbo.PHIEUTIEM", "MAGOIVX", "dbo.GOIVACXIN");
            DropForeignKey("dbo.CT_PHIEUTIEM", "MAPHIEUTIEM", "dbo.PHIEUTIEM");
            DropForeignKey("dbo.HOADON", "MAPHIEUTIEM", "dbo.PHIEUTIEM");
            DropForeignKey("dbo.HOADON", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.PHIEUNHAP", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.PHIEUXUAT", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.LOVACXIN", "MAPN", "dbo.PHIEUNHAP");
            DropForeignKey("dbo.PHIEUNHAP", "MANSX", "dbo.NHASANXUAT");
            DropForeignKey("dbo.CT_PHIEUXUAT", "MAPHIEUXUAT", "dbo.PHIEUXUAT");
            DropForeignKey("dbo.BACSI", "IDTAIKHOAN", "dbo.TAIKHOAN");
            DropForeignKey("dbo.NHANVIEN", "IDTAIKHOAN", "dbo.TAIKHOAN");
            DropForeignKey("dbo.TAIKHOAN", "MAQUYEN", "dbo.PHANQUYEN");
            DropForeignKey("dbo.PHIEUTIEM", "MAPHIEUKHAM", "dbo.PHIEUKHAM");
            DropForeignKey("dbo.PHIEUKHAM", "MAPHIEUDK", "dbo.PHIEUDANGKY");
            DropForeignKey("dbo.PHIEUDANGKY", "MAKH", "dbo.KHACHHANG");
            DropPrimaryKey("dbo.BACSI");
            DropPrimaryKey("dbo.COSO");
            DropPrimaryKey("dbo.KHO");
            DropPrimaryKey("dbo.LOAIVACXIN");
            DropPrimaryKey("dbo.VACXIN");
            DropPrimaryKey("dbo.GOIVACXIN");
            DropPrimaryKey("dbo.PHIEUTIEM");
            DropPrimaryKey("dbo.HOADON");
            DropPrimaryKey("dbo.NHANVIEN");
            DropPrimaryKey("dbo.PHIEUNHAP");
            DropPrimaryKey("dbo.LOVACXIN");
            DropPrimaryKey("dbo.NHASANXUAT");
            DropPrimaryKey("dbo.PHIEUXUAT");
            DropPrimaryKey("dbo.TAIKHOAN");
            DropPrimaryKey("dbo.PHANQUYEN");
            DropPrimaryKey("dbo.PHIEUKHAM");
            DropPrimaryKey("dbo.PHIEUDANGKY");
            DropPrimaryKey("dbo.KHACHHANG");
            AlterColumn("dbo.BACSI", "MABS", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.COSO", "MACS", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.KHO", "MAKHO", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.LOAIVACXIN", "MALOAI", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.VACXIN", "MAVX", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.GOIVACXIN", "MAGOIVX", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHIEUTIEM", "MAPHIEUTIEM", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.HOADON", "MAHD", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.NHANVIEN", "MANV", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHIEUNHAP", "MAPN", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.LOVACXIN", "MALO", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.NHASANXUAT", "MANSX", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHIEUXUAT", "MAPHIEUXUAT", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.TAIKHOAN", "IDTAIKHOAN", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHANQUYEN", "MAQUYEN", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHIEUKHAM", "MAPHIEUKHAM", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.PHIEUDANGKY", "MAPHIEUDK", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.KHACHHANG", "MAKH", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.BACSI", "MABS");
            AddPrimaryKey("dbo.COSO", "MACS");
            AddPrimaryKey("dbo.KHO", "MAKHO");
            AddPrimaryKey("dbo.LOAIVACXIN", "MALOAI");
            AddPrimaryKey("dbo.VACXIN", "MAVX");
            AddPrimaryKey("dbo.GOIVACXIN", "MAGOIVX");
            AddPrimaryKey("dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddPrimaryKey("dbo.HOADON", "MAHD");
            AddPrimaryKey("dbo.NHANVIEN", "MANV");
            AddPrimaryKey("dbo.PHIEUNHAP", "MAPN");
            AddPrimaryKey("dbo.LOVACXIN", "MALO");
            AddPrimaryKey("dbo.NHASANXUAT", "MANSX");
            AddPrimaryKey("dbo.PHIEUXUAT", "MAPHIEUXUAT");
            AddPrimaryKey("dbo.TAIKHOAN", "IDTAIKHOAN");
            AddPrimaryKey("dbo.PHANQUYEN", "MAQUYEN");
            AddPrimaryKey("dbo.PHIEUKHAM", "MAPHIEUKHAM");
            AddPrimaryKey("dbo.PHIEUDANGKY", "MAPHIEUDK");
            AddPrimaryKey("dbo.KHACHHANG", "MAKH");
            AddForeignKey("dbo.PHIEUTIEM", "MABS", "dbo.BACSI", "MABS");
            AddForeignKey("dbo.PHIEUKHAM", "MABS", "dbo.BACSI", "MABS");
            AddForeignKey("dbo.BACSI", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.KHO", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.NHANVIEN", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.PHIEUDANGKY", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.LOAIVACXIN", "MAKHO", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.PHIEUXUAT", "MAKHODICH", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.PHIEUXUAT", "MAKHONGUON", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.VACXIN", "MALOAI", "dbo.LOAIVACXIN", "MALOAI");
            AddForeignKey("dbo.LOVACXIN", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_GOIVX", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_PHIEUTIEM", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_PHIEUXUAT", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_GOIVX", "MAGOIVX", "dbo.GOIVACXIN", "MAGOIVX");
            AddForeignKey("dbo.PHIEUTIEM", "MAGOIVX", "dbo.GOIVACXIN", "MAGOIVX");
            AddForeignKey("dbo.CT_PHIEUTIEM", "MAPHIEUTIEM", "dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddForeignKey("dbo.HOADON", "MAPHIEUTIEM", "dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddForeignKey("dbo.HOADON", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.PHIEUNHAP", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.PHIEUXUAT", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.LOVACXIN", "MAPN", "dbo.PHIEUNHAP", "MAPN");
            AddForeignKey("dbo.PHIEUNHAP", "MANSX", "dbo.NHASANXUAT", "MANSX");
            AddForeignKey("dbo.CT_PHIEUXUAT", "MAPHIEUXUAT", "dbo.PHIEUXUAT", "MAPHIEUXUAT");
            AddForeignKey("dbo.BACSI", "IDTAIKHOAN", "dbo.TAIKHOAN", "IDTAIKHOAN");
            AddForeignKey("dbo.NHANVIEN", "IDTAIKHOAN", "dbo.TAIKHOAN", "IDTAIKHOAN");
            AddForeignKey("dbo.TAIKHOAN", "MAQUYEN", "dbo.PHANQUYEN", "MAQUYEN");
            AddForeignKey("dbo.PHIEUTIEM", "MAPHIEUKHAM", "dbo.PHIEUKHAM", "MAPHIEUKHAM");
            AddForeignKey("dbo.PHIEUKHAM", "MAPHIEUDK", "dbo.PHIEUDANGKY", "MAPHIEUDK");
            AddForeignKey("dbo.PHIEUDANGKY", "MAKH", "dbo.KHACHHANG", "MAKH");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.PHIEUDANGKY", "MAKH", "dbo.KHACHHANG");
            DropForeignKey("dbo.PHIEUKHAM", "MAPHIEUDK", "dbo.PHIEUDANGKY");
            DropForeignKey("dbo.PHIEUTIEM", "MAPHIEUKHAM", "dbo.PHIEUKHAM");
            DropForeignKey("dbo.TAIKHOAN", "MAQUYEN", "dbo.PHANQUYEN");
            DropForeignKey("dbo.NHANVIEN", "IDTAIKHOAN", "dbo.TAIKHOAN");
            DropForeignKey("dbo.BACSI", "IDTAIKHOAN", "dbo.TAIKHOAN");
            DropForeignKey("dbo.CT_PHIEUXUAT", "MAPHIEUXUAT", "dbo.PHIEUXUAT");
            DropForeignKey("dbo.PHIEUNHAP", "MANSX", "dbo.NHASANXUAT");
            DropForeignKey("dbo.LOVACXIN", "MAPN", "dbo.PHIEUNHAP");
            DropForeignKey("dbo.PHIEUXUAT", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.PHIEUNHAP", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.HOADON", "MANV", "dbo.NHANVIEN");
            DropForeignKey("dbo.HOADON", "MAPHIEUTIEM", "dbo.PHIEUTIEM");
            DropForeignKey("dbo.CT_PHIEUTIEM", "MAPHIEUTIEM", "dbo.PHIEUTIEM");
            DropForeignKey("dbo.PHIEUTIEM", "MAGOIVX", "dbo.GOIVACXIN");
            DropForeignKey("dbo.CT_GOIVX", "MAGOIVX", "dbo.GOIVACXIN");
            DropForeignKey("dbo.CT_PHIEUXUAT", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_PHIEUTIEM", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.CT_GOIVX", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.LOVACXIN", "MAVX", "dbo.VACXIN");
            DropForeignKey("dbo.VACXIN", "MALOAI", "dbo.LOAIVACXIN");
            DropForeignKey("dbo.PHIEUXUAT", "MAKHONGUON", "dbo.KHO");
            DropForeignKey("dbo.PHIEUXUAT", "MAKHODICH", "dbo.KHO");
            DropForeignKey("dbo.LOAIVACXIN", "MAKHO", "dbo.KHO");
            DropForeignKey("dbo.PHIEUDANGKY", "MACS", "dbo.COSO");
            DropForeignKey("dbo.NHANVIEN", "MACS", "dbo.COSO");
            DropForeignKey("dbo.KHO", "MACS", "dbo.COSO");
            DropForeignKey("dbo.BACSI", "MACS", "dbo.COSO");
            DropForeignKey("dbo.PHIEUKHAM", "MABS", "dbo.BACSI");
            DropForeignKey("dbo.PHIEUTIEM", "MABS", "dbo.BACSI");
            DropPrimaryKey("dbo.KHACHHANG");
            DropPrimaryKey("dbo.PHIEUDANGKY");
            DropPrimaryKey("dbo.PHIEUKHAM");
            DropPrimaryKey("dbo.PHANQUYEN");
            DropPrimaryKey("dbo.TAIKHOAN");
            DropPrimaryKey("dbo.PHIEUXUAT");
            DropPrimaryKey("dbo.NHASANXUAT");
            DropPrimaryKey("dbo.LOVACXIN");
            DropPrimaryKey("dbo.PHIEUNHAP");
            DropPrimaryKey("dbo.NHANVIEN");
            DropPrimaryKey("dbo.HOADON");
            DropPrimaryKey("dbo.PHIEUTIEM");
            DropPrimaryKey("dbo.GOIVACXIN");
            DropPrimaryKey("dbo.VACXIN");
            DropPrimaryKey("dbo.LOAIVACXIN");
            DropPrimaryKey("dbo.KHO");
            DropPrimaryKey("dbo.COSO");
            DropPrimaryKey("dbo.BACSI");
            AlterColumn("dbo.KHACHHANG", "MAKH", c => c.Int(nullable: false));
            AlterColumn("dbo.PHIEUDANGKY", "MAPHIEUDK", c => c.Int(nullable: false));
            AlterColumn("dbo.PHIEUKHAM", "MAPHIEUKHAM", c => c.Int(nullable: false));
            AlterColumn("dbo.PHANQUYEN", "MAQUYEN", c => c.Int(nullable: false));
            AlterColumn("dbo.TAIKHOAN", "IDTAIKHOAN", c => c.Int(nullable: false));
            AlterColumn("dbo.PHIEUXUAT", "MAPHIEUXUAT", c => c.Int(nullable: false));
            AlterColumn("dbo.NHASANXUAT", "MANSX", c => c.Int(nullable: false));
            AlterColumn("dbo.LOVACXIN", "MALO", c => c.Int(nullable: false));
            AlterColumn("dbo.PHIEUNHAP", "MAPN", c => c.Int(nullable: false));
            AlterColumn("dbo.NHANVIEN", "MANV", c => c.Int(nullable: false));
            AlterColumn("dbo.HOADON", "MAHD", c => c.Int(nullable: false));
            AlterColumn("dbo.PHIEUTIEM", "MAPHIEUTIEM", c => c.Int(nullable: false));
            AlterColumn("dbo.GOIVACXIN", "MAGOIVX", c => c.Int(nullable: false));
            AlterColumn("dbo.VACXIN", "MAVX", c => c.Int(nullable: false));
            AlterColumn("dbo.LOAIVACXIN", "MALOAI", c => c.Int(nullable: false));
            AlterColumn("dbo.KHO", "MAKHO", c => c.Int(nullable: false));
            AlterColumn("dbo.COSO", "MACS", c => c.Int(nullable: false));
            AlterColumn("dbo.BACSI", "MABS", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.KHACHHANG", "MAKH");
            AddPrimaryKey("dbo.PHIEUDANGKY", "MAPHIEUDK");
            AddPrimaryKey("dbo.PHIEUKHAM", "MAPHIEUKHAM");
            AddPrimaryKey("dbo.PHANQUYEN", "MAQUYEN");
            AddPrimaryKey("dbo.TAIKHOAN", "IDTAIKHOAN");
            AddPrimaryKey("dbo.PHIEUXUAT", "MAPHIEUXUAT");
            AddPrimaryKey("dbo.NHASANXUAT", "MANSX");
            AddPrimaryKey("dbo.LOVACXIN", "MALO");
            AddPrimaryKey("dbo.PHIEUNHAP", "MAPN");
            AddPrimaryKey("dbo.NHANVIEN", "MANV");
            AddPrimaryKey("dbo.HOADON", "MAHD");
            AddPrimaryKey("dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddPrimaryKey("dbo.GOIVACXIN", "MAGOIVX");
            AddPrimaryKey("dbo.VACXIN", "MAVX");
            AddPrimaryKey("dbo.LOAIVACXIN", "MALOAI");
            AddPrimaryKey("dbo.KHO", "MAKHO");
            AddPrimaryKey("dbo.COSO", "MACS");
            AddPrimaryKey("dbo.BACSI", "MABS");
            AddForeignKey("dbo.PHIEUDANGKY", "MAKH", "dbo.KHACHHANG", "MAKH");
            AddForeignKey("dbo.PHIEUKHAM", "MAPHIEUDK", "dbo.PHIEUDANGKY", "MAPHIEUDK");
            AddForeignKey("dbo.PHIEUTIEM", "MAPHIEUKHAM", "dbo.PHIEUKHAM", "MAPHIEUKHAM");
            AddForeignKey("dbo.TAIKHOAN", "MAQUYEN", "dbo.PHANQUYEN", "MAQUYEN");
            AddForeignKey("dbo.NHANVIEN", "IDTAIKHOAN", "dbo.TAIKHOAN", "IDTAIKHOAN");
            AddForeignKey("dbo.BACSI", "IDTAIKHOAN", "dbo.TAIKHOAN", "IDTAIKHOAN");
            AddForeignKey("dbo.CT_PHIEUXUAT", "MAPHIEUXUAT", "dbo.PHIEUXUAT", "MAPHIEUXUAT");
            AddForeignKey("dbo.PHIEUNHAP", "MANSX", "dbo.NHASANXUAT", "MANSX");
            AddForeignKey("dbo.LOVACXIN", "MAPN", "dbo.PHIEUNHAP", "MAPN");
            AddForeignKey("dbo.PHIEUXUAT", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.PHIEUNHAP", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.HOADON", "MANV", "dbo.NHANVIEN", "MANV");
            AddForeignKey("dbo.HOADON", "MAPHIEUTIEM", "dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddForeignKey("dbo.CT_PHIEUTIEM", "MAPHIEUTIEM", "dbo.PHIEUTIEM", "MAPHIEUTIEM");
            AddForeignKey("dbo.PHIEUTIEM", "MAGOIVX", "dbo.GOIVACXIN", "MAGOIVX");
            AddForeignKey("dbo.CT_GOIVX", "MAGOIVX", "dbo.GOIVACXIN", "MAGOIVX");
            AddForeignKey("dbo.CT_PHIEUXUAT", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_PHIEUTIEM", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.CT_GOIVX", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.LOVACXIN", "MAVX", "dbo.VACXIN", "MAVX");
            AddForeignKey("dbo.VACXIN", "MALOAI", "dbo.LOAIVACXIN", "MALOAI");
            AddForeignKey("dbo.PHIEUXUAT", "MAKHONGUON", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.PHIEUXUAT", "MAKHODICH", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.LOAIVACXIN", "MAKHO", "dbo.KHO", "MAKHO");
            AddForeignKey("dbo.PHIEUDANGKY", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.NHANVIEN", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.KHO", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.BACSI", "MACS", "dbo.COSO", "MACS");
            AddForeignKey("dbo.PHIEUKHAM", "MABS", "dbo.BACSI", "MABS");
            AddForeignKey("dbo.PHIEUTIEM", "MABS", "dbo.BACSI", "MABS");
        }
    }
}
