// <auto-generated />
namespace QuanLyTrungTamTiemChung.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lovxvx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lovxvx));
        
        string IMigrationMetadata.Id
        {
            get { return "202112200826371_lovx-vx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
